[package]
name = "escrow-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
escrow-core.workspace = true
escrow-adapter.workspace = true
thiserror.workspace = true

[dev-dependencies]

[lints]
workspace = true
