[package]
name = "escrow-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
escrow-domain.workspace = true
escrow-config.workspace = true
escrow-external.workspace = true
thiserror.workspace = true

[dev-dependencies]

[lints]
workspace = true
